Repository FRONT-END-BOOTCAMP-PLUS-4/lego, pull requests merged in 2025-04, with the labels that each got.

#11 초기 프로젝트 설정 & 문서 작업
  .github/PULL_REQUEST_TEMPLATE.md
  .github/images/1.png
  .github/images/2.png
  .github/images/architecture.png
  .github/images/erd.png
  .prettierrc
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
Labels: chore, docs

#12 시스템 아키텍처(페이지 라우터 구성 및 api 폴더 구성)
  .vscode/settings.json
  src/app/admin/questions/[id]/edit/page.tsx
  src/app/admin/questions/[id]/page.tsx
  src/app/admin/questions/create/page.tsx
  src/app/admin/questions/page.tsx
  src/app/api/admin/login/route.ts
  src/app/api/admin/questions/[id]/edit/route.ts
  src/app/api/admin/questions/[id]/route.ts
  src/app/api/admin/questions/route.ts
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/api/question/[id]/answer/[id]/comment/[id]/route.ts
  src/app/api/question/[id]/answer/[id]/comment/route.ts
  src/app/api/question/[id]/answer/[id]/like/route.ts
  src/app/api/question/[id]/answer/[id]/route.ts
  src/app/api/question/[id]/bookmark/route.ts
  src/app/api/question/[id]/route.ts
  src/app/api/question/route.ts
  src/app/api/user/[id]/answer/route.ts
  src/app/api/user/[id]/bookmark/route.ts
  src/app/api/user/[id]/comment/route.ts
  src/app/api/user/[id]/edit/route.ts
  src/app/api/user/[id]/like/route.ts
  src/app/api/user/[id]/route.ts
  src/app/login/page.tsx
  src/app/questions/[id]/answer/[id]/page.tsx
  src/app/questions/[id]/page.tsx
  src/app/questions/page.tsx
  src/app/users/activity/answer.tsx
  src/app/users/activity/page.tsx
  src/app/users/profile/page.tsx
Labels: chore

#13 시스템 아키텍처 초기 설계(app, api, application, domain, infra)
  src/application/usecase/admin/category/CreateCategoryUsecase.ts
  src/application/usecase/admin/category/GetCategoryUsecase.ts
  src/application/usecase/admin/category/dto/CategoryDto.ts
  src/application/usecase/admin/category/dto/CategoryListDto.ts
  src/application/usecase/admin/question/CreateQuestionUsecase.ts
  src/application/usecase/admin/question/DeleteQuestionUsecase.ts
  src/application/usecase/admin/question/GetQuestionListUsecase.ts
  src/application/usecase/admin/question/dto/QuestionDto.ts
  src/application/usecase/admin/question/dto/QuestionListDto.ts
  src/domain/enities/Admin.ts
  src/domain/enities/Answer.ts
  src/domain/enities/Bookmark.ts
  src/domain/enities/Category.ts
  src/domain/enities/Comment.ts
  src/domain/enities/Like.ts
  src/domain/enities/Question.ts
  src/domain/enities/Social.ts
  src/domain/enities/User.ts
  src/domain/repositories/AdminRepository.ts
  src/domain/repositories/AnswerRepository.ts
  src/domain/repositories/BookmarkRepository.ts
  src/domain/repositories/CategoryRepository.ts
  src/domain/repositories/CommentRepository.ts
  src/domain/repositories/LikeRepository.ts
  src/domain/repositories/QuestionRepository.ts
  src/domain/repositories/SocialRepository.ts
  src/domain/repositories/UserRepository.ts
  src/infra/repositories/supabase/SbAdminRepository.ts
  src/infra/repositories/supabase/SbAnswerRepository.ts
  src/infra/repositories/supabase/SbBookmarkRepository.ts
  src/infra/repositories/supabase/SbCategoryRepository.ts
  src/infra/repositories/supabase/SbCommentRepository.ts
  src/infra/repositories/supabase/SbLikeRepository.ts
  src/infra/repositories/supabase/SbQuestionRepository.ts
  src/infra/repositories/supabase/SbSocialRepository.ts
  src/infra/repositories/supabase/SbUserRepository.ts
Labels: chore

#25 [id] 폴더명 각 페이지별 아이디로 수정
  src/app/admin/questions/[questionid]/edit/page.tsx
  src/app/admin/questions/[questionid]/page.tsx
  src/app/api/question/[questionid]/answer/[answerid]/comment/[commentid]/route.ts
  src/app/api/question/[questionid]/answer/[answerid]/comment/route.ts
  src/app/api/question/[questionid]/answer/[answerid]/like/route.ts
  src/app/api/question/[questionid]/answer/[answerid]/route.ts
  src/app/api/question/[questionid]/bookmark/route.ts
  src/app/api/question/[questionid]/route.ts
  src/app/questions/[questionid]/answer/[answerid]/page.tsx
  src/app/questions/[questionid]/page.tsx
Labels: fix

#28 Feat/global style config
  components.json
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.tsx
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-Regular.woff2
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/components/ui/underLinetab.tsx
  src/lib/utils.ts
Labels: feat

#33 공통 사용 폰트 클래스 설정
  package-lock.json
  src/app/globals.css
  src/app/page.tsx
Labels: chore

#32 Feat/page admin(관리자 로그인 기능 및 페이지 구현)
  package-lock.json
  package.json
  src/app/admin/page.tsx
  src/app/admin/questions/[questionid]/page.tsx
  src/app/admin/questions/page.tsx
  src/app/api/admin/login/route.ts
  src/application/usecase/admin/login/LoginAdminUsecase.ts
  src/application/usecase/admin/login/dto/AdminLoginDto.ts
  src/application/usecase/admin/login/dto/AdminTokenDto.ts
  src/domain/enities/Admin.ts
  src/domain/repositories/AdminRepository.ts
  src/infra/repositories/supabase/SbAdminRepository.ts
  src/utils/supabase/server.ts
Labels: feat

#34 비밀번호 암호화 및 쿠키 설정
  src/app/admin/components/AdminHeader.tsx
  src/app/admin/page.tsx
  src/app/admin/questions/page.tsx
  src/app/api/admin/login/route.ts
  src/app/api/admin/logout/route.ts
  src/infra/repositories/supabase/SbAdminRepository.ts
  src/utils/supabase/server.ts
Labels: feat

#36 문제 답변 페이지 퍼블리싱
  public/assets/fonts/Pretendard-Bold.woff
  public/assets/fonts/Pretendard-Bold.woff2
  public/assets/fonts/Pretendard-Medium.woff
  public/assets/fonts/Pretendard-Medium.woff2
  public/assets/fonts/Pretendard-Regular.woff
  public/assets/fonts/Pretendard-Regular.woff2
  public/assets/icons/bookmark.svg
  public/assets/icons/bookmark_fill.svg
  public/assets/icons/left.svg
  public/assets/icons/like.svg
  public/assets/icons/like_fill.svg
  public/assets/icons/right.svg
  src/app/globals.css
  src/app/questions/[questionid]/page.tsx
  src/components/ui/card.tsx
Labels: feat

#40 관리자 로그인 리팩토링
  src/app/admin/page.tsx
  src/app/api/admin/login/route.ts
  src/application/usecase/admin/login/LoginAdminUsecase.ts
  src/infra/repositories/supabase/SbAdminRepository.ts
Labels: refactor

#44 로그인 페이지 UI 및 마이 페이지 안 나의 활동 페이지 UI 작업
  package-lock.json
  package.json
  public/assets/image/Bar.svg
  public/assets/image/Edit.svg
  public/assets/image/Github.svg
  public/assets/image/Google.svg
  public/assets/image/Logo.svg
  public/assets/image/github-142-svgrepo-com.svg
  public/assets/image/github-color-svgrepo-com.svg
  public/assets/image/google-color-svgrepo-com.svg
  src/app/globals.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/users/activity.tsx
  src/app/users/activity/answer.tsx
  src/app/users/myAnswer.tsx
  src/app/users/page.tsx
  src/app/users/profile.tsx
  src/application/usecase/user/CreateUserUsecase.ts
  src/application/usecase/user/GetUserUsecase.ts
  src/application/usecase/user/UpdateUserUsecase.ts
  src/application/usecase/user/dto/UserDto.ts
  src/domain/enities/Social.ts
  src/domain/enities/User.ts
  src/domain/repositories/SocialRepository.ts
  src/domain/repositories/UserRepository.ts
Labels: feat

#43 메인 페이지 UI 초기 퍼블리싱 및 공통 컴포넌트(Header, Footer) 구성
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/apple-touch-icon.png
  public/assets/images/category/1.svg
  public/assets/images/category/2.svg
  public/assets/images/category/3.svg
  public/assets/images/category/4.svg
  public/assets/images/category/5.svg
  public/assets/images/category/6.svg
  public/assets/questions/2/09-before,-after는-언제-사용하나요.md
  public/favicon-32x32 copy.png
  public/favicon.ico
  public/logo.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Head.tsx
  src/components/common/Header.tsx
  tailwind.config.js
Labels: chore, feat, style

#42 답변 상세 페이지 화면 초기 세팅
  src/app/admin/components/AdminHeader.tsx
  src/app/admin/page.tsx
  src/app/admin/questions/[questionid]/edit/page.tsx
  src/app/admin/questions/[questionid]/page.tsx
  src/app/admin/questions/create/page.tsx
  src/app/admin/questions/page.tsx
  src/app/api/admin/login/route.ts
  src/app/api/admin/logout/route.ts
  src/app/api/admin/questions/[id]/edit/route.ts
  src/app/api/admin/questions/[id]/route.ts
  src/app/api/admin/questions/route.ts
  src/app/questions/[questionid]/answer/[answerid]/page.tsx
  src/app/questions/[questionid]/answers/[answerid]/page.tsx
  src/application/usecase/admin/category/CreateCategoryUsecase.ts
  src/application/usecase/admin/category/GetCategoryUsecase.ts
  src/application/usecase/admin/category/dto/CategoryDto.ts
  src/application/usecase/admin/category/dto/CategoryListDto.ts
  src/application/usecase/admin/login/LoginAdminUsecase.ts
  src/application/usecase/admin/login/dto/AdminLoginDto.ts
  src/application/usecase/admin/login/dto/AdminTokenDto.ts
  src/application/usecase/admin/question/CreateQuestionUsecase.ts
  src/application/usecase/admin/question/DeleteQuestionUsecase.ts
  src/application/usecase/admin/question/GetQuestionListUsecase.ts
  src/application/usecase/admin/question/dto/QuestionDto.ts
  src/application/usecase/admin/question/dto/QuestionListDto.ts
  src/components/ui/textArea.tsx
  src/domain/enities/Admin.ts
  src/domain/repositories/AdminRepository.ts
  src/infra/repositories/supabase/SbAdminRepository.ts
Labels: feat

#47 유저 페이지 나의 활동 탭 컴포넌트 변환 작업
  package-lock.json
  public/assets/image/bookmark.svg
  public/assets/image/jsicon.svg
  src/app/users/activity.tsx
  src/app/users/bookmark.tsx
  src/app/users/comment.tsx
  src/app/users/likeAnswer.tsx
  src/app/users/myAnswer.tsx
  src/app/users/page.tsx
  src/app/users/profile.tsx
  src/application/usecase/user/CreateUserUsecase.ts
  src/application/usecase/user/GetUserUsecase.ts
  src/application/usecase/user/UpdateUserUsecase.ts
  src/application/usecase/user/dto/UserDto.ts
Labels: feat

#46 소셜 로그인(GitHub) 연동하기
  next.config.ts
  package-lock.json
  package.json
  src/app/api/auth/[provider]/route.ts
  src/app/auth/callback/page.tsx
  src/components/common/Header.tsx
  src/domain/enities/User.ts
  src/domain/entities/Answer.ts
  src/domain/entities/Bookmark.ts
  src/domain/entities/Category.ts
  src/domain/entities/Comment.ts
  src/domain/entities/Like.ts
  src/domain/entities/Question.ts
  src/domain/entities/Social.ts
  src/domain/entities/User.ts
  src/domain/repositories/AuthRepository.ts
  src/domain/repositories/SocialRepository.ts
  src/domain/repositories/UserRepository.ts
  src/infra/repositories/github/AuthRepository.ts
  src/store/useAuthStore.ts
  src/utils/jwt.ts
Labels: chore, feat

#50 마이페이지 구성하기
  package-lock.json
  package.json
  src/app/auth/callback/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/users/components/Activity.tsx
  src/app/users/components/Bookmark.tsx
  src/app/users/components/Comment.tsx
  src/app/users/components/History.tsx
  src/app/users/components/KakaoModal.tsx
  src/app/users/components/LikeAnswer.tsx
  src/app/users/components/MyAnswer.tsx
  src/app/users/components/Profile.tsx
  src/app/users/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/KakaoAlert.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/select.tsx
  src/components/ui/sonner.tsx
  src/components/ui/switch.tsx
  src/components/ui/underLinetab.tsx
  src/hooks/useHasHydrated.ts
  src/store/useProfileStore.ts
  src/utils/format.ts
Labels: chore, feat, style

#52 메인 페이지 UI 작업(로직 분리) 및 커스텀 UI(로딩, 404) 개선
  public/assets/images/loading.png
  public/assets/images/main/kakao-banner.png
  public/assets/images/not-found.png
  src/app/auth/callback/page.tsx
  src/app/components/AnswerList.tsx
  src/app/components/BookmarkList.tsx
  src/app/components/CategoryList.tsx
  src/app/components/Guide.tsx
  src/app/components/KakaoMessageBanner.tsx
  src/app/globals.css
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/users/components/Activity.tsx
  src/app/users/components/MyAnswer.tsx
  src/components/common/KakaoAlert.tsx
  src/utils/handleFormat.ts
  src/utils/handleKakao.ts
Labels: feat, style, asset

#53 질문 페이지 기능 구현
  package-lock.json
  package.json
  src/app/api/categories/route.ts
  src/app/api/questions/route.ts
  src/app/layout.tsx
  src/app/questions/page.tsx
  src/application/usecase/category/GetCategoryListUsecase.ts
  src/application/usecase/category/dto/CategoryDto.ts
  src/application/usecase/category/dto/CategoryListDto.ts
  src/application/usecase/question/GetQuestionListUsecase.ts
  src/application/usecase/question/dto/QuestionDto.ts
  src/domain/entities/Category.ts
  src/domain/entities/Question.ts
  src/domain/repositories/CategoryRepository.ts
  src/domain/repositories/QuestionRepository.ts
  src/infra/repositories/supabase/SbCategoryRepository.ts
  src/infra/repositories/supabase/SbQuestionRepository.ts
  src/utils/supabase/server.ts
Labels: feat, fix

#54 질문 상세 페이지 문제 조회 및 유저 답변 조회
  package-lock.json
  package.json
  src/app/api/answers/route.ts
  src/app/api/questions/[questionId]/route.ts
  src/app/api/questions/route.ts
  src/app/questions/[questionid]/componsts/AnswerPreviewCard.tsx
  src/app/questions/[questionid]/componsts/QuestionSolution.tsx
  src/app/questions/[questionid]/componsts/QusetionHeader.tsx
  src/app/questions/[questionid]/page.tsx
  src/app/questions/page.tsx
  src/application/answer/CreateAnswerUsecase.ts
  src/application/answer/dto/CreateAnswerDto.ts
  src/application/answer/dto/CreatedAnswerDto.ts
  src/application/answer/dto/GetAnswerDto.ts
  src/application/usecase/question/GetQuestionUsecase.ts
  src/application/usecase/question/dto/GetQuestionDto.ts
  src/domain/entities/Answer.ts
  src/domain/entities/AnswerView.ts
  src/domain/entities/Question.ts
  src/domain/entities/QuestionView.ts
  src/domain/repositories/AnswerRepository.ts
  src/domain/repositories/QuestionRepository.ts
  src/infra/repositories/supabase/SbAnswerRepository.ts
  src/infra/repositories/supabase/SbQuestionRepository.ts
  tailwind.config.js
Labels: chore, feat

#55 문제 리스트 페이지 및 API 구현
  package-lock.json
  package.json
  public/assets/images/QuestionsNotFound.png
  public/assets/images/banner.svg
  src/app/api/questions/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/questions/page.tsx
  src/application/usecase/question/GetQuestionListUsecase.ts
  src/application/usecase/question/dto/QuestionDto.ts
  src/domain/repositories/QuestionRepository.ts
  src/infra/repositories/supabase/SbQuestionRepository.ts
Labels: feat, fix, asset

#58 마이 페이지 - 나의 활동 API 연동
  custom.d.ts
  package-lock.json
  package.json
  src/app/api/users/activity/route.ts
  src/app/api/users/history/route.ts
  src/app/globals.css
  src/app/loading.tsx
  src/app/users/components/Activity.tsx
  src/application/user/GetUserActivityUsecase.ts
  src/application/user/dto/UserActivityDto.ts
  src/components/common/Header.tsx
  src/components/common/Loader.tsx
  src/domain/entities/UserActivity.ts
  src/domain/repositories/UserRepository.ts
  src/infra/repositories/supabase/SbUserRepository.ts
Labels: chore, feat, style

#61 질문별 다른 사용자 답변 조회 기능 구현
  src/app/api/questions/[questionId]/answers/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/questions/[questionid]/componsts/AnswerPreviewCard.tsx
  src/app/questions/[questionid]/componsts/OtherUsersAnswer.tsx
  src/app/questions/[questionid]/page.tsx
  src/application/usecase/answer/GetAnswerListUsecase.ts
  src/components/ui/card.tsx
  src/domain/entities/AnswerView.ts
  src/domain/repositories/AnswerRepository.ts
  src/infra/repositories/supabase/SbAnswerRepository.ts
  src/infra/repositories/supabase/SbQuestionRepository.ts
  src/utils/handleFormatDate.ts
Labels: feat

#63 마이 페이지 - 좋아요 한 답변(히스토리) API 연동
  src/app/api/users/history/likes/route.ts
  src/app/users/components/Bookmark.tsx
  src/app/users/components/LikeAnswer.tsx
  src/app/users/components/MyAnswer.tsx
  src/application/user/GetUserLikedAnswerUsecase.ts
  src/application/user/dto/UserLikedAnswerDto.ts
  src/domain/entities/UserLike.ts
  src/domain/repositories/UserRepository.ts
  src/infra/repositories/supabase/SbUserRepository.ts
Labels: feat

#64 마이 페이지 - 댓글(히스토리) API 연동
  src/app/api/users/history/comments/route.ts
  src/app/users/components/Comment.tsx
  src/application/user/GetUserCommentsUsecase.ts
  src/application/user/dto/UserCommentDto.ts
  src/domain/entities/UserComment.ts
  src/domain/repositories/UserRepository.ts
  src/infra/repositories/supabase/SbUserRepository.ts
Labels: feat

#66 답변 상세 조회 및 좋아요 기능 구현
  src/app/api/questions/[questionId]/answers/[userId]/route.ts
  src/app/api/questions/[questionId]/answers/route.ts
  src/app/questions/[questionid]/answers/[answerid]/components/AnswerContent.tsx
  src/app/questions/[questionid]/answers/[answerid]/components/AnswerContents.tsx
  src/app/questions/[questionid]/answers/[answerid]/components/AnswerHeader.tsx
  src/app/questions/[questionid]/answers/[answerid]/page.tsx
  src/app/questions/[questionid]/componsts/OtherUsersAnswer.tsx
  src/app/questions/[questionid]/page.tsx
  src/app/questions/page.tsx
  src/application/usecase/answer/GetAnswerUsecase.ts
  src/application/usecase/answer/dto/GetAnswerDto.ts
  src/domain/entities/AnswerView.ts
  src/domain/repositories/AnswerRepository.ts
  src/infra/repositories/supabase/SbAnswerRepository.ts
  src/infra/repositories/supabase/SbLikeRepository.ts
  src/infra/repositories/supabase/SbQuestionRepository.ts
  src/utils/handleFormatDate.ts
Labels: feat, style

#65 댓글 기능 추가 및 문제 리스트 기능 추가
  package-lock.json
  package.json
  public/assets/images/QuestionsLoading.png
  public/assets/images/QuestionsNotFound.png
  src/app/api/comments/[id]/route.ts
  src/app/api/comments/route.ts
  src/app/questions/[questionid]/answers/[answerid]/components/CommentSection.tsx
  src/app/questions/[questionid]/answers/[answerid]/page.tsx
  src/app/questions/page.tsx
  src/application/usecase/comment/CreateCommentUsecase.ts
  src/application/usecase/comment/DeleteCommentUsecase.ts
  src/application/usecase/comment/GetCommentListUsecase.ts
  src/application/usecase/comment/UpdateCommentUsecase.ts
  src/application/usecase/comment/dto/CommentDto.ts
  src/application/usecase/comment/dto/CreateCommentDto.ts
  src/application/usecase/comment/dto/CreatedCommentDto.ts
  src/application/usecase/comment/dto/UpdateCommentDto.ts
  src/domain/entities/Comment.ts
  src/domain/repositories/CommentRepository.ts
  src/infra/repositories/supabase/SbCommentRepository.ts
Labels: feat, fix

#67 메인 페이지 API 연동 및 마이페이지 일부 수정
  src/app/api/home/route.ts
  src/app/components/AnswerList.tsx
  src/app/components/BookmarkList.tsx
  src/app/users/components/Comment.tsx
  src/app/users/components/LikeAnswer.tsx
  src/application/usecase/home/GetHomeDataUsecase.ts
  src/domain/entities/HomePopularAnswer.ts
  src/domain/entities/HomePopularQuestion.ts
  src/domain/repositories/HomeRepository.ts
  src/infra/repositories/supabase/SbHomeRepository.ts
Labels: feat, fix

#68 공통 헤터 푸터 디자인 정리
  public/charactor.svg
  public/logo.png
  public/logo.svg
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/MailAlert.tsx
Labels: style

#69 댓글 수정, 삭제 API 버그 픽스 및 수정
  src/app/api/comments/[id]/route.ts
Labels: fix

#70 아이콘 변경, hover 등 추가 작업
  public/assets/icons/bookmark.svg
  public/assets/icons/bookmark_fill.svg
  public/assets/icons/kakao.svg
  public/assets/icons/left.svg
  public/assets/icons/like.svg
  public/assets/icons/like_fill.svg
  public/assets/icons/right.svg
  public/logoImg.svg
  src/app/api/questions/[questionId]/answers/[userId]/route.ts
  src/app/api/questions/[questionId]/answers/route.ts
  src/app/api/questions/[questionId]/route.ts
  src/app/components/AnswerList.tsx
  src/app/components/BookmarkList.tsx
  src/app/components/CategoryList.tsx
  src/app/components/Empty.tsx
  src/app/components/Guide.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/questions/[questionid]/answers/[answerid]/components/AnswerContent.tsx
  src/app/questions/[questionid]/answers/[answerid]/page.tsx
  src/app/questions/[questionid]/componsts/Alert.tsx
  src/app/questions/[questionid]/componsts/OtherUsersAnswer.tsx
  src/app/questions/[questionid]/componsts/QusetionHeader.tsx
  src/app/questions/[questionid]/page.tsx
  src/app/questions/page.tsx
  src/app/users/components/Activity.tsx
  src/app/users/components/Bookmark.tsx
  src/app/users/components/Comment.tsx
  src/app/users/components/LikeAnswer.tsx
  src/app/users/components/MyAnswer.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Loader.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/utils/handleFormatDate.ts
Labels: style

#71 메인 페이지 - 구독 배너 스타일 변경
  package-lock.json
  package.json
  public/assets/images/main/email.png
  public/assets/images/main/email_after.png
  public/assets/images/main/email_before.png
  src/app/components/EmailBanner.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/slider.tsx
Labels: feat, style

#73 메인 간격 수정
  src/app/components/AnswerList.tsx
  src/app/components/BookmarkList.tsx
  src/app/components/CategoryList.tsx
  src/app/components/EmailBanner.tsx
Labels: style

#74 메인 페이지, 마이 페이지 eslint 오류 수정
  src/domain/entities/HomePopularAnswer.ts
  src/infra/repositories/supabase/SbHomeRepository.ts
  src/infra/repositories/supabase/SbUserRepository.ts
  src/lib/mail/getQuestion.js
Labels: fix

#76 문제 리스트 오류 수정
  src/infra/repositories/supabase/SbQuestionRepository.ts
Labels: fix

#79 배포 환경 시 로그인 에러 수정
  src/app/api/auth/[provider]/route.ts
  src/app/api/questions/[questionId]/answers/[userId]/route.ts
  src/app/api/questions/[questionId]/route.ts
  src/app/auth/callback/page.tsx
  src/app/login/page.tsx
  src/infra/repositories/auth/GitHubAuthRepository.ts
  src/infra/repositories/auth/GoogleAuthRepository.ts
Labels: chore, fix

#80 fix: 마이페이지 api 일부 데이터 미반환 오류 수정
  src/infra/repositories/supabase/SbUserRepository.ts
Labels: fix

#83 600px 이하 레이아웃 깨짐 수정
  public/assets/icons/left.svg
  public/assets/icons/like.svg
  public/assets/icons/like_fill.svg
  public/assets/icons/right.svg
  src/app/components/AnswerList.tsx
  src/app/components/BookmarkList.tsx
  src/app/components/CategoryList.tsx
  src/app/components/EmailBanner.tsx
  src/app/components/Guide.tsx
  src/app/globals.css
  src/app/questions/[questionid]/answers/[answerid]/components/AnswerContent.tsx
  src/app/questions/[questionid]/componsts/OtherUsersAnswer.tsx
  src/app/questions/[questionid]/componsts/QusetionHeader.tsx
  src/app/questions/page.tsx
  src/app/users/components/Activity.tsx
  src/app/users/components/Comment.tsx
  src/app/users/components/MyAnswer.tsx
  src/app/users/page.tsx
  src/components/ui/badge.tsx
Labels: style

#82 메인 페이지 api 최적화 및 이메일 설정 안내문구 추가
  src/app/components/AnswerList.tsx
  src/app/components/BookmarkList.tsx
  src/app/layout.tsx
  src/app/users/page.tsx
  src/components/common/Header.tsx
Labels: refactor

#84 URL 오류 수정
  src/app/questions/[questionid]/answers/[answerid]/components/CommentSection.tsx
  src/app/questions/page.tsx
Labels: fix

#86 문제 리스트 반응형 디자인 추가
  src/app/questions/page.tsx
Labels: style

#87 답변 저장 로직 개선 및 알림(Alert) 추가
  src/app/components/GithubLoginNotice.tsx
  src/app/questions/[questionid]/componsts/Alert.tsx
  src/app/questions/[questionid]/componsts/OtherUsersAnswer.tsx
  src/app/questions/[questionid]/page.tsx
  src/application/usecase/answer/CreateAnswerUsecase.ts
  src/components/ui/alert-dialog.tsx
  src/utils/handleCheckUser.ts
Labels: feat, style

#88 댓글 없을 때 마진 추가
  src/app/questions/[questionid]/answers/[answerid]/components/CommentSection.tsx
Labels: fix, style

#89 구독 메일 발송 시 연동링크 수정
  src/lib/mail/sendMail.js
Labels: chore

#90 로고 및 로딩 변경
  public/logoImg.svg
  src/app/login/page.tsx
  src/app/questions/[questionid]/answers/[answerid]/components/AnswerContent.tsx
  src/app/questions/[questionid]/components/Alert.tsx
  src/app/questions/[questionid]/components/OtherUsersAnswer.tsx
  src/app/questions/[questionid]/components/QuestionSolution.tsx
  src/app/questions/[questionid]/components/QusetionHeader.tsx
  src/app/questions/[questionid]/page.tsx
  src/components/common/Header.tsx
  src/components/common/Loader.tsx
Labels: feat, style
